# SonataAdminBundle Routing Configuration
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

rudz_fresh:
    resource: "@RudzFreshBundle/Resources/config/routing.yml"
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# SonataMediaBundle Routing Configuration
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media