# Set parameters here for the production target of the app
parameters:
    database_driver:   pdo_mysql
    database_host:     ~
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~
