# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
#    rudz.service_name_with_setter:
#        class: Rudz\FreshBundle\ClassName
#        calls:
#            - [setContainer, ["@service_container"]]
#            - [setParameters, ["plain_value", "%parameter_name%"]]

#    rudz.service_name_with_construct:
#        class: Rudz\FreshBundle\ClassName
#        arguments: ["@service_container", "plain_value", "%parameter_name%"]
