# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    secret: FreshSymfonyIsSoFresh!

framework:
    secret: "%secret%"
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true
